<a href="https://colab.research.google.com/github/chitnapak/Data-Bootcamp12/blob/main/Essential_Python_for_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential Python for DA

- OOP in Depth
- Try Except
- Context Manager
- Read & Write Files in Python
- Numerical Python & Pandas
- Requests (API)

# OOP

* attributes : name,age
* methods: function bark() hbd()

In [59]:
class Dog:
  def __init__(self, name, species, age):
    self.name = name
    self.species = species
    self.age = age

  def bark(self):
    print(f"{self.name} is braking Hong Hong")

  def hbd(self):
    self.age +=1

In [60]:
## attributes
dog1 = Dog("milo", "Chihuahua", 3)
dog2 = Dog("davod", "Husky", 2)

In [61]:
print(f"{dog1.name} is {dog1.species}")

milo is Chihuahua

In [62]:
print(f"{dog2.name} is {dog2.species}")

davod is Husky

In [63]:
dog1.bark()

milo is braking Hong Hong

In [64]:
print(dog1.age)
dog1.hbd()
print(dog1.age)

3
4

In [65]:
## homeworkd OOP for an ATM

## deposit, withdraw, check balance, OTP, order coffee, pay bill, internet etc.

In [66]:
class ATM:
  def __init__(self, username, bank, amount):
    self.username = username
    self.bank = bank
    self.amount = amount

  def __str__(self):
    return f"{self.username} uses {self.bank} and has {self.amount} THB in an account."

  def check_balance(self):
    print(f"Balance: {self.amount} THB")

  def deposit(self, saving):
    self.amount += saving
    print(f"Deposit {saving} THB")
    print(f"Balance: {self.amount} THB")

In [67]:
toy = ATM("kasidis toy", "scb", 100)

In [68]:
toy.check_balance()

Balance: 100 THB

In [69]:
toy.deposit(1)

Deposit 1 THB
Balance: 101 THB

In [70]:
toy.check_balance()

Balance: 101 THB

In [80]:
print(toy)

kasidis toy uses scb and has 101 THB in an account.

In [81]:
## super class

In [71]:
class Person:
  def __init__(self, name ,age):
    self.name = name
    self.age = age

## extention
class Employee(Person):
  def __init__(self, name, age, company):
    super().__init__(name, age)
    self.company =company

  def greeting(self):
    print("Hello world")

In [72]:
person1 = Person("Bob", 25)

In [73]:
person2 = Employee("Bob", 25, "Google")

In [82]:
person2.greeting()

Hello world

# Try Except Block

In [1]:
try:
  result = 1/0
except:
  print("Error")

Error

In [75]:
!ls

drive  sample_data

In [3]:
!cat hotel.csv

hotel_id,name,city,star_rating,price_per_night
101,Grand Plaza,New York,5,350
102,Ocean View,Miami,4,220
103,Mountain Retreat,Denver,4,185
104,The Urban Stay,Chicago,3,140
105,Sunset Resort,Los Angeles,5,410
106,Desert Inn,Phoenix,3,95
107,Heritage House,Boston,4,210
108,Lakeside Lodge,Seattle,3,130
109,Golden Gate Suites,San Francisco,5,380
110,Central Boutique,Austin,4,195

In [4]:
## read file
import csv

In [5]:
try:
  file = open("hotel.csv", "r") #r w a (อ่าน เขียน append)

  data = csv.reader(file)

  for row in data:
    print(row)

  file.close()
except:
  print("Error")
finally:
  print("Done")

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']
Done

In [6]:
# context manager ไม่ต้องมีเปิดปิด ไฟล์
read_data = []

with open("hotel.csv", "r") as file:
  data = csv.reader(file)
  for row in data:
    read_data.append(row)

In [7]:
read_data

[['hotel_id', 'name', 'city', 'star_rating', 'price_per_night'],
 ['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [8]:
# header
read_data[0]

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [10]:
# body data
read_data[1: ]

[['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [16]:
## for loop to calculate avg. price per night
prices = []

for row in read_data[1: ]:
  prices.append(int(row[4]))

print(f"AVG price per night: {sum(prices)/ len(prices)}")

AVG price per night: 231.5

In [13]:
# modern python
import pandas as pd

df = pd.read_csv("hotel.csv")

df.head()

   hotel_id              name         city  star_rating  price_per_night
0       101       Grand Plaza     New York            5              350
1       102        Ocean View        Miami            4              220
2       103  Mountain Retreat       Denver            4              185
3       104    The Urban Stay      Chicago            3              140
4       105     Sunset Resort  Los Angeles            5              410

In [14]:
df["price_per_night"].mean()

np.float64(231.5)

# **Read & Write Files**

In [18]:
import csv

In [17]:
# write file + context manager
head = ["id", "name", "city"]
body = [
    [1, "Bob", "New York"],
    [2, "Alice", "London"]
]

with open("school.csv", "w") as file:
  writer = csv.writer(file)
  writer.writerow(head) #ใส่ค่าเพียง 1 แถว
  writer.writerows(body) #ใส่ค่ามากกว่า 1 แถว

In [19]:
!ls

drive  hotel.csv  sample_data  school.csv

In [20]:
!cat school.csv

id,name,city
1,Bob,New York
2,Alice,London

In [21]:
# modern python
import pandas as pd

df = pd.read_csv("school.csv")

df.head()

   id   name      city
0   1    Bob  New York
1   2  Alice    London

In [22]:
df.to_csv("school2.csv")

In [23]:
!ls

drive  hotel.csv  sample_data  school2.csv  school.csv

In [ ]:
# read data from internet

In [24]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

In [37]:
import pandas as pd
df_penguins = pd.read_csv(url)

In [26]:
df_penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [36]:
df_penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [27]:
## select column
df_penguins[["island","body_mass_g"]].head(10)

      island  body_mass_g
0  Torgersen       3750.0
1  Torgersen       3800.0
2  Torgersen       3250.0
3  Torgersen          NaN
4  Torgersen       3450.0
5  Torgersen       3650.0
6  Torgersen       3625.0
7  Torgersen       4675.0
8  Torgersen       3475.0
9  Torgersen       4250.0

In [40]:
## filter rows
df_penguins[["species","body_mass_g","island"]]\
  .query("species == 'Adelie' and island == 'Dream' ")\
  .head(10)

   species  body_mass_g island
30  Adelie       3250.0  Dream
31  Adelie       3900.0  Dream
32  Adelie       3300.0  Dream
33  Adelie       3900.0  Dream
34  Adelie       3325.0  Dream
35  Adelie       4150.0  Dream
36  Adelie       3950.0  Dream
37  Adelie       3550.0  Dream
38  Adelie       3300.0  Dream
39  Adelie       4650.0  Dream

In [ ]:
# R VS Python
# df %>%
#   select(species, body_mass_g) %>%
#   filter(species == "Adelie") %>%
#   head(10)

# df.select()\
#   .filter()\
#   .head()

In [29]:
# filter without query()
df_penguins[df_penguins["species"] == "Adelie"][["species","sex"]]

    species     sex
0    Adelie    MALE
1    Adelie  FEMALE
2    Adelie  FEMALE
3    Adelie     NaN
4    Adelie  FEMALE
..      ...     ...
147  Adelie  FEMALE
148  Adelie  FEMALE
149  Adelie    MALE
150  Adelie  FEMALE
151  Adelie    MALE

[152 rows x 2 columns]

In [30]:
# requests api

# Requests

In [ ]:
import requests

# api endpoint
url = "https://swapi.info/api/people/1"

In [ ]:
response = requests.get(url)

In [ ]:
response.json()

In [ ]:
response.json()["name"]

In [ ]:
## for loop
import requests
import time

names = []


for i in range(10):
  url = f"https://swapi.info/api/people/{i+1}"
  response = requests.get(url)
  response.json = response.json()
  names.append(response.json["name"])
  time.sleep(1)

print(names)

# **Part 2**
# Essential Concepts in Python

* lambda
* map, filter
* import module
* regular expression
* numpy + pandas
* json

In [ ]:
# create a new function in python
def hello():
  return "hollo world"

In [ ]:
hello()

In [ ]:
def add_two_nums(a, b):
  return a + b

In [ ]:
add_two_nums(5,2)

In [ ]:
# lambda
test = lambda x: print(x)

In [ ]:
test("toy")

In [ ]:
add_two = lambda num:print(num + 2)

In [ ]:
add_two(2)

In [ ]:
test2 = lambda x, y: x+y

In [ ]:
test2(2,3)

In [ ]:
# map / filter
# iterable (adj)
scores = [2, 5, 10, 12]

In [ ]:
def grading(score):
  if score >=5 :
    print("passed")
  else:
    print("failed")

In [ ]:
# map
list(map(grading, scores))

In [ ]:
# add five to scores
list(map(lambda x: x+5, scores))

In [ ]:
# filter
scores

In [ ]:
list(filter(lambda x: x>= 5, scores))

In [ ]:
# module / library
import random
class ATM:
  def __init__(self, name, balance):
    self.name = name
    self.balance = balance

  def __str__(self):
    return f"Hello {self.name} your balance is {self.balance}"

  def get_otp(self):
    otp = random.randint(1000, 9999)
    return f"Your Requested OTP is {otp}"

In [ ]:
my_account = ATM("Bob", 1000)

In [ ]:
print(my_account)

In [ ]:
my_account.get_otp()

In [ ]:
# standard python modules
import random

In [ ]:
fruits = ["orange", "apple", "banana"]

In [ ]:
for i in range(10):
  random.seed(42) # ล็อคผล
  print(random.choice(fruits))

In [ ]:
random.randint

In [ ]:
# import regular expression
import re

In [ ]:
text = "a duck cost $80 usd per piece."

In [ ]:
re.search("duck", text)

In [ ]:
text[2:6]

In [ ]:
re.findall("duck",text)

In [ ]:
! pwd

In [ ]:
## install new library/ mudule (ต้องต่อ internet ก่อนเสมอ)
!pip install pandas

In [ ]:
!pip install numpy

In [ ]:
## server cannot connect to internet
#

In [ ]:
# working with json
# JavaScript Object NOtation

profile = {
    "name": "toy",
    "age": 24,
    "movie" : ["toy story", "toy monster"]
}

In [ ]:
type(profile)

In [ ]:
# import json
import json

with open("profile.json", "w") as file:
  json.dump(profile, file)

In [ ]:
!cat profile.json

In [ ]:
# read json file
with open("profile.json", "r") as file:
  data = json.load(file)

data

In [ ]:
data["movie"][1]

In [ ]:
# numpy
# numerical python = matrix / computing
import random

nums = [ ]

for i in range(10):
  nums.append(random.randint(1,10))

print(nums)

In [ ]:
sum(nums)

In [ ]:
import numpy as np

In [ ]:
nums

In [ ]:
print(np.sum(nums),
      np.mean(nums),
      np.var(nums))

In [ ]:
# change to numpy array
nums = np.array(nums)
type(nums)

In [ ]:
nums

In [ ]:
# numpy method
print(nums.sum(),
      nums.max()
)

In [ ]:
# import pandas + numpy
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({
    "name": ["toy", "top", "tap"],
    "income": [1,2,3]
})

df["income"].sum()

In [ ]:
# web scraping

In [ ]:
!pip install gazpacho

In [ ]:
# import library (modules)
import requests
from gazpacho import Soup

In [ ]:
url = "https://raw.githubusercontent.com/toyeiei/python-test-bc12/refs/heads/main/index.html"

In [ ]:
# get request
response = requests.get(url)

In [ ]:
response.status_code

In [ ]:
web =Soup(response.text)

In [ ]:
web

In [ ]:
web.find("h2")

In [ ]:
for h2 in web.find("li"):
  print(h2.strip())